# Generated by Django 5.0.6 on 2024-07-04 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='messages',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='cterted',
            new_name='created',
        ),
    ]
